### ISSUE TITLE
[VS2019 Preview3.0 16.2.0][WPF Designer]Drag dll to toolbox, no useable Control

### ISSUE THREAD

**Issue by TempeBrennan** [microsoft/xaml-designer-extensibility-samples#1]
# Issue Title

Donwload Microsoft WPF custom control sample found an issue.

# General
VS: VS2019 Preview3.0 16.2.0

download project from :
[Microsoft sample site](https://github.com/microsoft/xaml-designer-extensibility-samples)

I found a custom control in project CustomControlLibrary.WpfCore CustomButton.cs file.
```c#
    public class CustomButton : Button
    {
        public CustomButton()
        {
            // The GetIsInDesignMode check and the following design-time 
            // code are optional and shown only for demonstration.
            if (DesignerProperties.GetIsInDesignMode(this))
            {
                Content = "Design mode active";
            }
        }
    }
```

build,
drag output CustomControlLibrary.WpfCore.dll to a toolbox tab.
then found a control CustomButton appear. It's ok.

Then I add some code to this sample:
```c#
    public class CustomButton : Button
    {
        public CustomButton()
        {
            // The GetIsInDesignMode check and the following design-time 
            // code are optional and shown only for demonstration.
            if (DesignerProperties.GetIsInDesignMode(this))
            {
                Content = "Design mode active";
            }
        }
    }

    // ADD this code
    public class CustomButtonHelper
    {

    }
```
Rebuild
drag output CustomControlLibrary.WpfCore.dll to a toolbox tab.
current tab onlys shows there is no usable control.

If you delete added code then rebuild. This issue disappear.
I think maybe I miss some settings in Microsoft sample.

Is there anybody meet the same question?  Please give me some suggetions. Thanks a lot!

**Comment by hemantbajpai4** [comment]
This is a VS issue, not related to extensibility sample code.

**Comment by benZhai01** [comment]
@hemantbajpai4 so where can I follow the VS issue? someone else has reported it?

**Comment by hemantbajpai4** [comment]
Something similar is reported here: https://developercommunity.visualstudio.com/content/problem/591937/wpf-designer-extension-still-not-available-for-net.html
