### ISSUE TITLE
How to debug extension code?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/xaml-designer-extensibility-samples#3]
Having looked at and run the code for the CustomControlLibrary.WpfCore sample, it's not clear how to step through the extensions under the debugger.
Please can you add instructions for this.

**Comment by hemantbajpai4** [comment]
You just need to open another VS instance and attach to devenv.exe, below are the steps:

open sln
build sln
start another VS instance
open the sln there too
attach debugger in one VS instance to the other instance (devenv.exe)
put a breakpoint in Metadata.AttributeTable getter
open mainwindow.xaml in the debuggee
breakpoint hit

**Comment by mrlacey** [comment]
Got this working, thanks.
For anyone else who comes here, I've found that to apply code changes I need to also do the following.

- Build the project in Visual Studio
- See that it builds but fails to copy the generated assembly
- Close Visual Studio (all instances with the project open)
- Build the project again from the command line `dotnet build .\CustomControlLibrary.WpfCore.DesignTools.csproj` (this skips the build step because it sees nothing has changed but manages to copy the assembly because VS is no longer locking the file)
- Re-open VS and enjoy the ability to use compiled, changed code.
