### ISSUE TITLE
CustomButton Adapters not working in sample

### ISSUE THREAD

**Issue by mrlacey** [microsoft/xaml-designer-extensibility-samples#4]
Using the current CustomControlLibrary.WpfCore sample, `CustomButtonParentAdapter` and `CustomButtonPlacementAdapter` do not appear to be working.

All other functionality behaves as [documented in the repo](https://github.com/microsoft/xaml-designer-extensibility-samples/blob/master/CustomControlLibrary.WpfCore/README.md) but I see no different behavior when dragging and dropping a control (TextBox, or any other control) from the Toolbox onto the button surface. Can you confirm this definitely works? and if there are any other factors to be aware of to see this working?

Using Visual Studio Enterprise 2019 Preview 16.4.0 preview 1.0

**Comment by hemantbajpai4** [comment]
Thanks for pointing this out, this broke because we changed some APIs recently. Now it should work as expected.
