### ISSUE TITLE
Is the ComplexNumber Editor display in the current sample correct?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/xaml-designer-extensibility-samples#5]
When setting a complex number in the editor in the sample, the value displayed in the property window seems incorrect (highlighted in image below.)

![image](https://user-images.githubusercontent.com/189547/66860092-60302400-ef84-11e9-94ff-577d7c280dd4.png)

Is this the correct behavior?

I was expecting the property editor to also show `-1,-3`.

**Comment by hemantbajpai4** [comment]
It should work with 16.4 preview 2.

**Comment by mrlacey** [comment]
Yes, I can confirm it works in 16.4p2
