### ISSUE TITLE
How to package XAML Designer extensions

### ISSUE THREAD

**Issue by mrlacey** [microsoft/xaml-designer-extensibility-samples#6]
This functionality is great. Thanks for finally starting to add extensibility to the XAML designer.

Please can you provide information on how any extensions that make use of this functionality can be packaged and anything to be aware of when doing so.

Can they be packaged in both a VSIX? and in a NuGet package added to the project?
Are there any limitations or restrictions when installed via one over the other? (Like how Roslyn analyzers can be installed via either but there are configuration limitations when in a VSIX.)

**Comment by hemantbajpai4** [comment]
The recommended way to deploy .designtools.dll extensions is by including them in the same NuGet package as the actual control library. The .designtools.dll should go in a Design folder:
lib\netcoreapp30\ControlLibrary.dll
lib\netcoreapp30\Design\ControlLibrary.DesignTools.dll
