### ISSUE TITLE
Extensibility less stable in 16.4p2

### ISSUE THREAD

**Issue by mrlacey** [microsoft/xaml-designer-extensibility-samples#7]
When using the sample extensibility project in 16.4preview1 a window displaying the XAML designer (for DemoApplication.MainWindow.xaml) would occasionally crash.
After updating to 16.4preview2 attempting to use the new extensibility functionality under a debugger, this has frequently caused the whole instance of Visual Studio being debugged to crash.

I'm happy to provide more information on this if you can provide advice on how to capture it. I can't see any obvious logs with anything relevant.

Also, are issues directly connect to XAML extensibility better reported here? Or via general VS feedbak?

**Comment by hemantbajpai4** [comment]
can you share project and steps which leads to crash? you can post general VS feedback or post it here as well.

**Comment by mrlacey** [comment]
Scratch this. 16.4p2 seems less stable for projects more than just the sample project in this repo.
