### ISSUE TITLE
CustomButtonParentAdapter called incorrectly

### ISSUE THREAD

**Issue by mrlacey** [microsoft/xaml-designer-extensibility-samples#8]
`CustomButtonParentAdapter.CanParent` is called multiple times (by `[ExternalCode]') even when nothing is being dropped on the designer.

The `childType` is just an `Object` so I can't provide more information on where this is coming from.

I'm using VS16.4 preview 2

**Comment by hemantbajpai4** [comment]
This is by design.

**Comment by mrlacey** [comment]
It might be worth updating the comment [here](https://github.com/microsoft/xaml-designer-extensibility-samples/blob/9315b69e697a41f7bb66226de56f9777c8529935/CustomControlLibrary.WpfCore/CustomControlLibrary.WpfCore.DesignTools/CustomButtonParentAdapter.cs#L14) to say it may also be called at other times too.

**Comment by hemantbajpai4** [comment]
done.
